export const cityList = {
  group: [
    { cityName: "基隆市", enName: "Keelung" },
    { cityName: "臺北市", enName: "Taipei" },
    { cityName: "新北市", enName: "NewTaipei" },
    { cityName: "桃園市", enName: "Taoyuan" },
    { cityName: "新竹市", enName: "Hsinchu" },
    { cityName: "新竹縣", enName: "HsinchuCounty" },
    { cityName: "苗栗縣", enName: "MiaoliCounty" },
    { cityName: "臺中市", enName: "Taichung" },
    { cityName: "彰化縣", enName: "ChanghuaCounty" },
    { cityName: "南投縣", enName: "NantouCounty" },
    { cityName: "雲林縣", enName: "YunlinCounty" },
    { cityName: "嘉義市", enName: "Chiayi" },
    { cityName: "嘉義縣", enName: "ChiayiCounty" },
    { cityName: "臺南市", enName: "Tainan" },
    { cityName: "高雄市", enName: "Kaohsiung" },
    { cityName: "屏東縣", enName: "PingtungCounty" },
    { cityName: "臺東縣", enName: "TaitungCounty" },
    { cityName: "花蓮縣", enName: "HualienCounty" },
    { cityName: "宜蘭縣", enName: "YilanCounty" },
    { cityName: "澎湖縣", enName: "PenghuCounty" },
    { cityName: "金門縣", enName: "KinmenCounty" },
    { cityName: "連江縣", enName: "LienchiangCounty" },
  ],
};
